version: '3.7'

x-stas: &default-stas
    image: ghcr.io/linux-nvme/nvme-stas:main
    build:
      context: .
    volumes:
        - /run/dbus:/run/dbus
        - /etc/nvme:/etc/nvme
        - stas_data:/run/stas
    privileged: true
    network_mode: host

services:
  stafd:
    <<: *default-stas
    environment:
      RUNTIME_DIRECTORY: /run/stas
      XDG_CACHE_HOME: /var/cache/stafd
      PYTHONUNBUFFERED: 1
    command: -u /usr/sbin/stafd
  stacd:
    <<: *default-stas
    environment:
      RUNTIME_DIRECTORY: /run/stas
      XDG_CACHE_HOME: /var/cache/stacd
      PYTHONUNBUFFERED: 1
    command: -u /usr/sbin/stacd

volumes:
    stas_data: