name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install -y libjson-c-dev python3-pyudev python3-systemd python3-gi meson libsystemd-dev libgirepository1.0-dev
          python -m pip install --upgrade pip pylint pyflakes lxml dasbus pyudev systemd PyGObject

      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: test

      - name: Pylint
        run: |
          pylint --version;
          PYTHONPATH=build/subprojects/libnvme pylint --rcfile=test/pylint.rc *.py staslib
      - name: Pyflakes
        if: always()
        run: |
          python -m pip install --upgrade pip pyflakes
          pyflakes --version
          pyflakes *.py staslib
